title: Bitcoin and Energy
author: btc_rauru
email: btc_rauru@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  In this blog, I'll teach you everything you need to understand about energy, 
  economics and energy, and finally, Bitcoin and energy. It will address fundamental
  economic and energy/phyics principles and teach you how to better think about them.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
